version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
    ports:
      - 3306:3306
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    environment:
      - DATABASE_HOST=mysql-docker-container
      - DATABASE_PORT=3306
      - DATABASE_NAME=spring_app_db
      - DATABASE_USER=app_user
      - DATABASE_PASSWORD=test123 
      
